name: Rust

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*' # trigger on version tags like v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Cache dependencies
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Build release
      run: cargo build --release

    - name: Run post-build script
      run: cargo run --bin postbuild --release
    
    - name: Package target/release
      run: |
        cd target/release
        zip -r release.zip *

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
